version: "3"
services:
  analyzer-service:
    container_name: analyzer-service
    build:
      context: ./analyzer-service
    volumes:
      - ./analyzer-service:/analyzer-service
    ports:
      - 4000:4000
    networks:
      - backend
    depends_on:
      - mongo
    restart: on-failure
    environment:
      - ALPHAVANTAGE_API_KEY=Z59MIQGN9I6S666Q
      - DATABASE_USERNAME=jschnebly
      - DATABASE_PASSWORD=Wolfpack2019

  app-client:
    container_name: app-client
    build:
      context: ./app-client
    volumes:
      - ./app-client:/app-client
      - /app-client/node_modules
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true

  app-server:
    container_name: app-server
    build:
      context: ./app-server
    volumes:
      - ./app-server:/app-server
      - /app-server/node_modules
    ports:
      - 3001:3001
    networks:
      - backend
    depends_on:
      - mongo
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=ieen
      - TOKEN_SECRET=papabravoindia

  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-admin:
    container_name: mongo-admin
    image: mrvautin/adminmongo:latest
    environment:
      - CONN_NAME=admin-connection
      - DB_HOST=mongo
      - DB_PORT=27017
      - HOST=0.0.0.0
    ports:
      - 1234:1234
      - 27018:1234
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge