version: "3"
services:
  analyzer-service:
    container_name: analyzer-service
    build:
      context: ./analyzer-service
      dockerfile: Dockerfile
    volumes:
      - ./analyzer-service:/analyzer-service
      - /analyzer-service
    ports:
      - 4000:4000
    restart: on-failure

  app-client:
    container_name: app-client
    build:
      context: ./app-client
      dockerfile: Dockerfile
    volumes:
      - ./app-client:/app-client
      - /app-client/node_modules
    ports:
      - 3000:3000
    links:
      - app-server
    restart: on-failure

  app-server:
    container_name: app-server
    build:
      context: ./app-server
      dockerfile: Dockerfile
    volumes:
      - ./app-server:/app-server
      - /app-server/node_modules
    ports:
      - 3001:3001
    links:
      - mongo
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

  mongo-admin:
    container_name: mongo-admin
    image: mrvautin/adminmongo
    environment:
      - CONN_NAME=admin-connection
      - DB_HOST=mongo
      - DB_PORT=27017
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 27018:1234
