version: "3"
services:
  analyzer-service:
    image: ayovev/project-blue-is_analyzer-service
    container_name: analyzer-service
    ports:
      - 4000
    networks:
      - backend
    environment:
      ALPHAVANTAGE_API_KEY:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_HOST:
      DATABASE_NAME:
      PYTHON_ENV: production
    restart: on-failure

  app:
    image: ayovev/project-blue-is_app
    container_name: app
    ports:
      - 8080
    networks:
      - backend
    environment:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_HOST:
      DATABASE_NAME:
      EMAIL:
      EMAIL_PASSWORD:
      NODE_ENV: production
      TOKEN_SECRET:
    restart: on-failure

networks:
  backend:
    driver: bridge
